services:
  postgres:
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./resources:/docker-entrypoint-initdb.d/
    networks:
      - network_0

  api:
    image: api_tcg
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/database
    ports:
      - "3000:3000"
    networks:
      - network_0

  app:
    image: app_tcg
    build:
      context: app
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://api:3000
    ports:
      - "80:4321"
    networks:
      - network_0
networks:
  network_0: {}
