services:
  postgres:
    image: postgres:17.2-alpine3.21
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./resources:/docker-entrypoint-initdb.d/